# Generated by Django 2.2.4 on 2019-09-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190928_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
