# Generated by Django 2.2.4 on 2019-12-09 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 18, 51, 52, 47335)),
        ),
    ]
