# Generated by Django 2.2.4 on 2020-01-05 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zip', models.IntegerField(default='')),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2020, 1, 5, 11, 43, 47, 146742))),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 11, 43, 47, 146742)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
